from enum import Enum


class State(Enum):
    INITIAL = "Initial"
    ERROR = "Error"
    KEY = "Key"
    SINGLE_QUOTED_KEY = "SingleQuotedKey"
    DOUBLE_QUOTED_KEY = "DoubleQuotedKey"
    EXPECT_OPERATOR = "ExpectOperator"
    VALUE = "Value"
    EXPECT_VALUE = "ExpectValue"
    SINGLE_QUOTED_VALUE = "SingleQuotedValue"
    DOUBLE_QUOTED_VALUE = "DoubleQuotedValue"
    KEY_VALUE_OPERATOR = "KeyValueOperator"
    BOOL_OP_DELIMITER = "BoolOpDelimiter"
    EXPECT_BOOL_OP = "ExpectBoolOp"
    KEY_OR_BOOL_OP = "KeyOrBoolOp"
    EXPECT_NOT_TARGET = "ExpectNotTarget"
    EXPECT_IN_KEYWORD = "ExpectInKeyword"
    EXPECT_HAS_KEYWORD = "ExpectHasKeyword"
    EXPECT_LIST_START = "ExpectListStart"
    IN_LIST_VALUE = "InListValue"
    IN_LIST_SINGLE_QUOTED_VALUE = "InListSingleQuotedValue"
    IN_LIST_DOUBLE_QUOTED_VALUE = "InListDoubleQuotedValue"
    EXPECT_LIST_COMMA_OR_END = "ExpectListCommaOrEnd"
    EXPECT_LIST_VALUE = "ExpectListValue"
    EXPECT_LIKE_KEYWORD = "ExpectLikeKeyword"
